#!/usr/bin/env bash
#source ~/.config/sway/scripts/sway-colors

window_prefix="<span foreground=\"#956dca\">» </span>"
drun_prefix="<span foreground=\"#5599E2\">> </span>"
run_prefix="<span foreground=\"#69bfce\">$ </span>"
combi_prompt=">>>"

rofi -show combi \
     -modes combi \
     -combi-modes "window,drun,run" \
     -display-window "$window_prefix" \
     -display-drun "$drun_prefix" \
     -display-run "$run_prefix" \
     -display-combi "$combi_prompt" \

